# Generated by Django 2.1 on 2020-03-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0063_auto_20200320_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Данные подвала', 'verbose_name_plural': 'Данные подвала'},
        ),
        migrations.AlterModelOptions(
            name='footercont',
            options={'verbose_name': 'Тип подвала', 'verbose_name_plural': 'Тип подвала'},
        ),
        migrations.AlterModelOptions(
            name='navconstruct',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Основное меню'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Информация страницы', 'verbose_name_plural': 'Информация страницы'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Фото примера', 'verbose_name_plural': 'Фото примера'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Типы примеров на странице', 'verbose_name_plural': 'Типы примеров на странице'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Картинки слайдера страницы', 'verbose_name_plural': 'Картинки слайдера страницы'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети и данные заголовка'},
        ),
        migrations.AlterModelOptions(
            name='subnavigator',
            options={'verbose_name': 'Подраздел', 'verbose_name_plural': 'Подменю'},
        ),
        migrations.AlterModelOptions(
            name='subsubnav',
            options={'verbose_name': 'Подраздел подраздела', 'verbose_name_plural': 'Подменю подменю'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Информация подвала', 'verbose_name_plural': 'Информация подвала'},
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='href2',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='href3',
        ),
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='example',
            name='example',
            field=models.ForeignKey(help_text='привязка к типу примера', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='information.Projects', verbose_name='Тип примеров'),
        ),
        migrations.AlterField(
            model_name='example',
            name='href',
            field=models.CharField(blank=True, help_text='URL картинки в приблежениии', max_length=200, verbose_name='URL картинки'),
        ),
        migrations.AlterField(
            model_name='example',
            name='keywords',
            field=models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='example',
            name='projectname',
            field=models.CharField(blank=True, help_text='название проекта', max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='example',
            name='slug',
            field=models.SlugField(blank=True, help_text='название url адреса', null=True, unique=True, verbose_name='URL адрес'),
        ),
        migrations.AlterField(
            model_name='example',
            name='src',
            field=models.CharField(blank=True, help_text='URL картинки', max_length=200, verbose_name='URL картинки'),
        ),
        migrations.AlterField(
            model_name='example',
            name='title',
            field=models.CharField(blank=True, help_text='обозначается без ., пример type1', max_length=100, verbose_name='Тип примеров'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='classdir',
            field=models.CharField(blank=True, help_text='Стиль контейнера', max_length=100, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='classul',
            field=models.CharField(blank=True, help_text='указать стиль', max_length=100, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='hreflogo',
            field=models.CharField(blank=True, help_text='URL лого', max_length=100, verbose_name='URL лого'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(help_text='название раздела подвала', max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='type',
            field=models.ForeignKey(help_text='выбрать тип подвала', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='information.Footercont', verbose_name='Тип подвала'),
        ),
        migrations.AlterField(
            model_name='footercont',
            name='classdiv',
            field=models.CharField(blank=True, help_text='Стиль контейнера', max_length=100, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='footercont',
            name='classname',
            field=models.CharField(help_text='указать стиль', max_length=100, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='footercont',
            name='title',
            field=models.CharField(help_text='название типа подвала', max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='descrtionmeta',
            field=models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='hreflogo',
            field=models.CharField(blank=True, help_text='URL картинка', max_length=100, verbose_name='URL картинка'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='keywordsmeta',
            field=models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='name',
            field=models.CharField(help_text='название основного раздела', max_length=30, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='section',
            field=models.TextField(help_text='название секции, необязательно', null=True, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='slug',
            field=models.SlugField(blank=True, help_text='название url адреса', null=True, unique=True, verbose_name='URL адрес'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='template_name',
            field=models.CharField(help_text='название html файла', max_length=30, null=True, verbose_name='Название html'),
        ),
        migrations.AlterField(
            model_name='navconstruct',
            name='title',
            field=models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='projname',
            field=models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtext', to='information.Subnavigator', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='page',
            name='quote',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subname',
            field=models.ForeignKey(help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='information.Navconstruct', verbose_name='Основное меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='textdown',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='textup',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='название заголовка', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='href1',
            field=models.CharField(blank=True, help_text='URL фото примера', max_length=200, verbose_name='URL фото'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.ForeignKey(help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='information.Example', verbose_name='Пример'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='dafilter',
            field=models.CharField(blank=True, help_text='обозначается через ., пример .type1', max_length=100, verbose_name='Обозначени типа'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='href',
            field=models.CharField(blank=True, help_text='ссылка на страницу, если на той же, по умолчанию #', max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projname',
            field=models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproj', to='information.Subnavigator', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subname',
            field=models.ForeignKey(help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj', to='information.Navconstruct', verbose_name='Основное меню'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, help_text='название тимпа примеров', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='hreflogo',
            field=models.CharField(blank=True, help_text='URL картинки', max_length=100, verbose_name='URL картинки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(help_text='имя картинки на слайдере', max_length=30, verbose_name='Имя картинки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='projname',
            field=models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subslider', to='information.Subnavigator', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='social',
            name='classname',
            field=models.CharField(help_text='стиль выбирается из https://fontawesome.ru/all-icons/ ', max_length=30, verbose_name='стиль иконки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='href',
            field=models.URLField(help_text='URL сети или сайта', null=True, verbose_name='URL компании'),
        ),
        migrations.AlterField(
            model_name='social',
            name='social',
            field=models.BooleanField(help_text='Если соц сеть,то ставим галочку', verbose_name='Соц сети'),
        ),
        migrations.AlterField(
            model_name='social',
            name='text',
            field=models.TextField(blank=True, help_text='Описание компании или сети', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(help_text='название подменю', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='descrtionmeta',
            field=models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='hreflogo',
            field=models.CharField(blank=True, help_text='URL картинка', max_length=100, verbose_name='URL картинка'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='keywordsmeta',
            field=models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='name',
            field=models.CharField(help_text='название основного раздела', max_length=30, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='projname',
            field=models.ForeignKey(blank=True, help_text='привязка к подвалу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='information.Footercont', verbose_name='Тип подвала'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='section',
            field=models.TextField(help_text='название секции, необязательно', null=True, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='slug',
            field=models.SlugField(blank=True, help_text='название url адреса', null=True, unique=True, verbose_name='URL адрес'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='subname',
            field=models.ForeignKey(blank=True, help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='information.Navconstruct', verbose_name='Основное меню'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='template_name',
            field=models.CharField(help_text='название html файла', max_length=30, null=True, verbose_name='Название html'),
        ),
        migrations.AlterField(
            model_name='subnavigator',
            name='title',
            field=models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='descrtionmeta',
            field=models.TextField(blank=True, help_text='описание страницы в поискаовика', max_length=300, verbose_name='Описание страницы'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='hreflogo',
            field=models.CharField(blank=True, help_text='URL картинка', max_length=100, verbose_name='URL картинка'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='keywordsmeta',
            field=models.TextField(blank=True, help_text='ключевые слова для поисковика', max_length=300, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='name',
            field=models.CharField(help_text='название основного раздела', max_length=30, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='section',
            field=models.TextField(help_text='название секции, необязательно', null=True, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='slug',
            field=models.SlugField(blank=True, help_text='название url адреса', null=True, unique=True, verbose_name='URL адрес'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='subname',
            field=models.ForeignKey(help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='information.Subnavigator', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='template_name',
            field=models.CharField(help_text='название html файла', max_length=30, null=True, verbose_name='Название html'),
        ),
        migrations.AlterField(
            model_name='subsubnav',
            name='title',
            field=models.CharField(blank=True, help_text='описание заголовка в строке браузера', max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='text',
            name='footertext',
            field=models.TextField(blank=True, help_text='описание подвала', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='text',
            name='subname',
            field=models.ForeignKey(help_text='привязка к данным подвала', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textsub', to='information.Footer', verbose_name='Данные подвала'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, help_text='название раздела подвала', max_length=30, verbose_name='Наименование'),
        ),
    ]
