# Generated by Django 2.1 on 2020-03-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0064_auto_20200325_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактная информация для контакты', 'verbose_name_plural': 'Контактная информация для контакты'},
        ),
        migrations.AlterModelOptions(
            name='contdecr',
            options={'verbose_name': 'Загловки на странице контакты', 'verbose_name_plural': 'Загловки на странице контакты'},
        ),
        migrations.AlterModelOptions(
            name='etapy',
            options={'verbose_name': 'Этапы работ на главной странице', 'verbose_name_plural': 'Этапы работ на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Наполнение списка', 'verbose_name_plural': 'Наполнение списка'},
        ),
        migrations.AlterModelOptions(
            name='faqblock',
            options={'verbose_name': 'Всплвающие списки на старнице', 'verbose_name_plural': 'Всплвающие списки на старнице'},
        ),
        migrations.AlterModelOptions(
            name='mpage',
            options={'verbose_name': 'Информации для главной', 'verbose_name_plural': 'Информации для главной'},
        ),
        migrations.AlterModelOptions(
            name='pagenext',
            options={'verbose_name': 'Иинформация страницы', 'verbose_name_plural': 'Иинформация страницы'},
        ),
        migrations.AlterModelOptions(
            name='pageproject',
            options={'verbose_name': 'Иинформация страницы', 'verbose_name_plural': 'Иинформация страницы'},
        ),
        migrations.AlterModelOptions(
            name='pictslider',
            options={'verbose_name': 'Слайдер на главной странице', 'verbose_name_plural': 'Слайдер на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='short',
            options={'verbose_name': 'Краткая информация примера', 'verbose_name_plural': 'Краткая информация примера'},
        ),
        migrations.AlterModelOptions(
            name='textslider',
            options={'verbose_name': 'Слайдер текст на главной странице', 'verbose_name_plural': 'Слайдер текст на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name': 'Список информации для главной', 'verbose_name_plural': 'Список информации для главной'},
        ),
        migrations.AddField(
            model_name='etapy',
            name='alt',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
        migrations.AddField(
            model_name='etapy',
            name='alt1',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
        migrations.AddField(
            model_name='example',
            name='alt',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
        migrations.AddField(
            model_name='pagenext',
            name='alt',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='alt',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='answer',
            field=models.TextField(blank=True, help_text='ответ списка', verbose_name='Ответ списка'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(blank=True, help_text='стиль выбирается из https://fontawesome.ru/all-icons/ ', max_length=50, verbose_name='стиль иконки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='имя списка', max_length=50, verbose_name='Имя списка'),
        ),
        migrations.AlterField(
            model_name='contdecr',
            name='title1',
            field=models.CharField(blank=True, help_text='Загловок на стр контакты', max_length=100, verbose_name='Загловок на стр контакты'),
        ),
        migrations.AlterField(
            model_name='contdecr',
            name='title2',
            field=models.CharField(blank=True, help_text='Загловок на стр контакты', max_length=100, verbose_name='Загловок на стр контакты'),
        ),
        migrations.AlterField(
            model_name='contdecr',
            name='title3',
            field=models.CharField(blank=True, help_text='Загловок на стр контакты', max_length=100, verbose_name='Загловок на стр контакты'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='answer',
            field=models.TextField(blank=True, help_text='ответ списка', verbose_name='Ответ списка'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='answernext',
            field=models.TextField(blank=True, help_text='ответ списка', verbose_name='Ответ списка'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='href',
            field=models.CharField(blank=True, help_text='URL фото примера', max_length=200, verbose_name='URL фото'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='href1',
            field=models.CharField(blank=True, help_text='URL фото примера', max_length=200, verbose_name='URL фото1'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='name',
            field=models.CharField(help_text='имя списка', max_length=50, verbose_name='Имя списка'),
        ),
        migrations.AlterField(
            model_name='etapy',
            name='namenext',
            field=models.CharField(blank=True, help_text='имя списка', max_length=50, verbose_name='Имя списка'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='ответ списка', verbose_name='Ответ списка'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.ForeignKey(help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='information.Faqblock', verbose_name='Основное меню'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='имя списка', max_length=200, verbose_name='Имя списка'),
        ),
        migrations.AlterField(
            model_name='faqblock',
            name='name',
            field=models.CharField(help_text='название списка и страница', max_length=100, verbose_name='Название списка'),
        ),
        migrations.AlterField(
            model_name='mpage',
            name='name',
            field=models.CharField(blank=True, help_text='заголовок', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mpage',
            name='textblock',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='mpage',
            name='textblock1',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='mpage',
            name='title',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок1'),
        ),
        migrations.AlterField(
            model_name='mpage',
            name='title1',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок2'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='blockquote',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='paragraph',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='projname',
            field=models.ForeignKey(blank=True, help_text='привязка к подменю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnext', to='information.Subnavigator', verbose_name='Подменю'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='quote',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст4'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='subname',
            field=models.ForeignKey(help_text='привязка к основному меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='information.Navconstruct', verbose_name='Основное меню'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='textdown',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст5'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='textnext',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст2'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='textup',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст3'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='title',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок3'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='titlecoloumn',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок1'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='titlenext',
            field=models.CharField(blank=True, help_text='заголовок', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='titleparagraph',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок2'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='urljpg',
            field=models.CharField(blank=True, help_text='URL фото', max_length=100, verbose_name='URL фото'),
        ),
        migrations.AlterField(
            model_name='pagenext',
            name='urlvideo',
            field=models.URLField(blank=True, help_text='URL видео с ютуба', max_length=100, verbose_name='URL видео с ютуба'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='blockquote',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='name',
            field=models.ForeignKey(help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageproject', to='information.Example', verbose_name='Пример'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='paragraph',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст1'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='textnext',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст2'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='titlecoloumn',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок1'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='titlenext',
            field=models.CharField(blank=True, help_text='заголовок', max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='titleparagraph',
            field=models.CharField(blank=True, help_text='заголовок', max_length=100, verbose_name='Заголовок2'),
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='urlvideo',
            field=models.URLField(blank=True, help_text='URL видео с ютуба', max_length=100, verbose_name='URL видео с ютуба'),
        ),
        migrations.AlterField(
            model_name='pictslider',
            name='hreflogo',
            field=models.CharField(help_text='URL фото', max_length=100, verbose_name='URL фото'),
        ),
        migrations.AlterField(
            model_name='short',
            name='caregory',
            field=models.CharField(help_text='Категория', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='short',
            name='duration',
            field=models.CharField(help_text='Сроки выполнения', max_length=100, verbose_name='Сроки выполнения'),
        ),
        migrations.AlterField(
            model_name='short',
            name='fokus',
            field=models.CharField(help_text='Фокус', max_length=100, verbose_name='Фокус'),
        ),
        migrations.AlterField(
            model_name='short',
            name='name',
            field=models.ForeignKey(help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short', to='information.Example', verbose_name='Пример'),
        ),
        migrations.AlterField(
            model_name='short',
            name='namecategory',
            field=models.CharField(help_text='Название категории', max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='short',
            name='nameduration',
            field=models.CharField(help_text='Название сроков', max_length=30, verbose_name='Название сроков'),
        ),
        migrations.AlterField(
            model_name='short',
            name='namefokus',
            field=models.CharField(help_text='Название фокус', max_length=30, verbose_name='Название фокус'),
        ),
        migrations.AlterField(
            model_name='short',
            name='namesite',
            field=models.CharField(help_text='Название адреса', max_length=30, verbose_name='Название адреса'),
        ),
        migrations.AlterField(
            model_name='short',
            name='predescription',
            field=models.TextField(blank=True, help_text='Краткое описание', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='short',
            name='site',
            field=models.CharField(help_text='Адрес проекта', max_length=100, verbose_name='Адрес проекта'),
        ),
        migrations.AlterField(
            model_name='textslider',
            name='clas',
            field=models.CharField(blank=True, help_text='текст', max_length=20, verbose_name='Класс текста слайдера'),
        ),
        migrations.AlterField(
            model_name='textslider',
            name='picture',
            field=models.ForeignKey(help_text='привязка к слайдеру главной страницы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='information.Pictslider', verbose_name='Слайдер главной страницы'),
        ),
        migrations.AlterField(
            model_name='textslider',
            name='textbldown',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст слайедра'),
        ),
        migrations.AlterField(
            model_name='textslider',
            name='textblock',
            field=models.TextField(blank=True, help_text='текст', verbose_name='Текст слайедра'),
        ),
        migrations.AlterField(
            model_name='values',
            name='answer',
            field=models.TextField(blank=True, help_text='ответ списка', verbose_name='Ответ списка'),
        ),
        migrations.AlterField(
            model_name='values',
            name='icon',
            field=models.CharField(blank=True, help_text='стиль выбирается из https://fontawesome.ru/all-icons/ ', max_length=50, verbose_name='стиль иконки'),
        ),
        migrations.AlterField(
            model_name='values',
            name='name',
            field=models.CharField(help_text='имя списка', max_length=50, verbose_name='Имя списка'),
        ),
    ]
